# Generated by Django 5.1.7 on 2025-04-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
