# Generated by Django 5.1.7 on 2025-04-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_first_name_remove_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
