# Generated by Django 5.1.7 on 2025-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Name'),
        ),
    ]
