# Generated by Django 5.1.7 on 2025-03-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('client', '0002_remove_client_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='client.client'),
        ),
    ]
