# Generated by Django 5.1.7 on 2025-03-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
